/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exponential.backoff.and.jitter;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
    }
}
